logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Extended]
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
included-patches = "'Change player flyout panel toggles' 'Enable debug logging' 'Hide player buttons background' 'Hide player chapters' 'Spoof player parameters'"
excluded-patches = "'Custom package name' 'Hide voice search button' 'Theme' 'Tuck away preferences' 'Visual preferences icons'"
rv-brand = "ReVanced Extended"
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
