enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/MatadorProBr/revanced-extended-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Extended]
app-name = "YouTube"
patches-source = "rufusin/revanced-patches"
integrations-source = "rufusin/revanced-integrations"
cli-source = "inotia00/revanced-cli"
included-patches = "'Enable debug logging'"
excluded-patches = "'Custom package name' 'Theme'"
rv-brand = "ReVanced Extended"
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
